# 基于的基础镜像
FROM node:lts-alpine as build-stage

# 设置code文件夹是工作目录
WORKDIR /app

# 安装支持
COPY package*.json ./
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm install

# 代码添加
COPY . .

CMD ["npm run serve"]
